version: '3'

services:
  nginx-a:
    image: nginx:stable
    volumes:
      - ./dockers/config/nginx/conf.d/sites.conf:/etc/nginx/conf.d/sites.conf
      - ./dockers/config/nginx/conf.d/upstream.conf:/etc/nginx/conf.d/upstream.conf
      - ./dockers/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./:/var/www
    depends_on:
      - php-a
      - postgresql-a
    ports:
      - 80:80
    networks:
      - app-network
    command: 'nginx -g "daemon off;"'
  postgresql-a:
    image: postgres:12.4
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: db_test
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - app-network
  php-a:
    build:
      context: ./dockers/compose/php
    volumes:
      - ./dockers/config/php/www.conf:/usr/local/etc/php-fpm.d/www.conf
      - ./:/var/www
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.0.104 remote_enable=1 remote_autostart=off remote_port=9008 max_nesting_level=500"
      PHP_IDE_CONFIG: "serverName=1"
      DB_HOST: postgresql-a
      DB_PORT: 5432
      DB_DATABASE: db_test
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      DB_CONNECTION: pgsql
      APP_URL: http://mytest.local
      APP_ENV: local
      APP_DEBUG: "true"
    depends_on:
      - postgresql-a
    ports:
      - 9000:9000
      - 22:22
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
